# Generated by Django 4.1.3 on 2022-11-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=20)),
                ("l_name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("mobile_no", models.BigIntegerField(max_length=50)),
                ("gender", models.CharField(max_length=20)),
            ],
        ),
    ]
