# Generated by Django 4.1.3 on 2022-11-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup",
            old_name="f_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="signup",
            old_name="l_name",
            new_name="last_name",
        ),
    ]
