# Generated by Django 4.1.3 on 2022-11-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0002_rename_f_name_signup_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("cat_image", models.ImageField(upload_to="upload/category")),
            ],
        ),
    ]
