# Generated by Django 4.1.3 on 2022-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0003_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(upload_to="upload/category/"),
        ),
    ]
