# Generated by Django 4.1.3 on 2022-11-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0005_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup",
            name="mobile_no",
            field=models.BigIntegerField(),
        ),
    ]
