# Generated by Django 4.1.3 on 2022-11-18 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0008_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 21, 32, 17, 784938)
            ),
        ),
    ]
