# Generated by Django 4.1.3 on 2022-11-18 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0009_alter_order_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=20)),
                ("last", models.CharField(max_length=20)),
                ("fav", models.CharField(max_length=50, unique=True)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 22, 3, 27, 553481)
            ),
        ),
    ]
