# Generated by Django 4.1.3 on 2022-11-23 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0010_table_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 23, 21, 18, 4, 341004)
            ),
        ),
        migrations.CreateModel(
            name="Norder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(max_length=400, null=True)),
                ("mobile_no", models.BigIntegerField()),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 23, 21, 18, 4, 342004)
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shopify.signup"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopify.product",
                    ),
                ),
            ],
        ),
    ]
