# Generated by Django 4.1.3 on 2022-11-23 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0012_remove_norder_address_remove_norder_mobile_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="norder",
            name="ooo",
            field=models.ForeignKey(
                default=21,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopify.order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="norder",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 23, 21, 42, 32, 713565)
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 23, 21, 42, 32, 713565)
            ),
        ),
    ]
