# Generated by Django 4.1.3 on 2022-11-23 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopify", "0013_norder_ooo_alter_norder_date_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="norder",
            name="address",
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="norder",
            name="mobile_no",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="norder",
            name="customer",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="norder",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 24, 1, 16, 33, 204580)
            ),
        ),
        migrations.AlterField(
            model_name="norder",
            name="product",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 24, 1, 16, 33, 204580)
            ),
        ),
    ]
